volumes:
  db_storage:
  n8n_storage:

networks:
  internal:
    driver: bridge

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  postgres-mcp:
    image: crystaldba/postgres-mcp:latest
    restart: always
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_NON_ROOT_USER}:${POSTGRES_NON_ROOT_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: ["--access-mode=unrestricted", "--transport=sse"]
    ports:
      - "7777:8000"
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/sse || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    labels:
      - "mcp.endpoint=http://192.168.50.63:7777/sse"
      - "mcp.description=Postgres MCP Server - AI-powered database operations"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    environment:
      # postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      # n8n config
      - GENERIC_TIMEZONE=America/Denver
      - N8N_PROTOCOL=http
      - N8N_HOST=192.168.50.63
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
    ports:
      - "192.168.50.63:5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
      postgres-mcp:
        condition: service_started
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"